### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by bogdanliusik** [bogdanliusik/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by yaroslav-liusik** [comment]
<div class="social-icons">
   <a class="social-icon" href="https://www.linkedin.com/in/bohdan-liusik-3859231a8/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
   <a class="social-icon" href="https://github.com/BohdanLiuisk" target="_blank"><i class="fab fa-github"></i></a>
   <a class="social-icon" href="https://t.me/bohdanliusik" target="_blank"><i class="fab fa-telegram"></i></
</div>
